# Generated by Django 2.2.7 on 2019-11-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Autor nieznany', max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Brak typu', max_length=400),
        ),
    ]
