# Generated by Django 2.2.7 on 2019-12-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_auto_20191226_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Author unknown', max_length=100),
        ),
    ]
