# Generated by Django 2.2.7 on 2019-12-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
