# Generated by Django 2.2.7 on 2019-12-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_auto_20191205_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedProducts',
            new_name='OrderedProduct',
        ),
    ]
